#ifndef SRC_DEFINITIONS_H_
#define SRC_DEFINITIONS_H_

#define RIGHT_DRIVE_ONE 0
#define RIGHT_DRIVE_TWO 1
#define RIGHT_DRIVE_THREE 2

#define LEFT_DRIVE_ONE 6
#define LEFT_DRIVE_TWO 7
#define LEFT_DRIVE_THREE 8

#endif /* SRC_DEFINITIONS_H_ */
